#!/usr/bin/env python3
import math
from collections import Counter
from sys import argv
from sys import exit

def stock() -> dict:
    argc = 0
    key = argv[1]
    for c in argv[1]:
        argc += 1
    if argc == 1:
        mat = [0]
        mat[0] = ord(key[0])
    if argc > 1 and argc <= 4:
        mat = [[0, 0], [0, 0]]
        if argc >= 2:
            mat[0][0] = ord(key[0])
            mat[0][1] = ord(key[1])
        if argc >= 3:
            mat[1][0] = ord(key[2])
        if argc >= 4:
            mat[1][1] = ord(key[3])
    if argc > 4 and argc <= 9:
        mat = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
        mat[0][0] = ord(key[0])
        mat[0][1] = ord(key[1])
        mat[0][2] = ord(key[2])
        mat[1][0] = ord(key[3])
        mat[1][1] = ord(key[4])
        if argc >= 6:
            mat[1][2] = ord(key[5])
        if argc >= 7:
            mat[2][0] = ord(key[6])
        if argc >= 8:
            mat[2][1] = ord(key[7])
        if argc == 9:
            mat[2][2] = ord(key[8])
    return mat

def base():
    mat = stock()
    for nb in mat:
        print(nb)

base()
